.shared_hidden_key: &shared 
  before_script:
    - docker login -u "<username>" -p <password>

stages:
 - build_images
 - deploy
 
job1:
  tags:
    - micro_runner
  <<: *shared
  stage: build_images
  script:
  - docker build -t <image_name> .
  - docker push <image_name>

job2:
  tags:
    - micro_runner
  stage: deploy
  script:
  - ssh -i <AmazonCloudKey.pem> <username>@<host> 'bash -s' < deploy.sh